/* ================= EXECUTIVE PDF ================= */

async function exportExecutivePDF() {

    if (!businessData.length) {
        alert("No data to export.");
        return;
    }

    if (!canExportPDF()) return;
    if (typeof window.jspdf === "undefined") return;

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    const totalRevenue = sum("revenue");
    const totalProfit = sum("profit");
    const margin = totalRevenue ? ((totalProfit / totalRevenue) * 100).toFixed(1) : 0;
    const latest = businessData[businessData.length - 1];

    let y = 20;

    /* ===== LOGO ===== */

    if (companyLogoData && userPlan === "premium") {
        doc.addImage(companyLogoData, "PNG", 15, 10, 30, 30);
    }

    /* ===== TITLE ===== */

    doc.setFontSize(20);
    doc.setTextColor(40);
    doc.text("ImpactGrid Intelligence Report", 105, y, { align: "center" });
    y += 10;

    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text("Enterprise Performance Analysis", 105, y, { align: "center" });
    y += 20;

    /* ===== SUMMARY SECTION ===== */

    doc.setFontSize(14);
    doc.setTextColor(0);
    doc.text("Executive Summary", 20, y);
    y += 10;

    doc.setFontSize(11);

    doc.text("Total Revenue: " + formatCurrency(totalRevenue), 20, y);
    y += 8;

    doc.text("Total Profit: " + formatCurrency(totalProfit), 20, y);
    y += 8;

    doc.text("Profit Margin: " + margin + "%", 20, y);
    y += 8;

    doc.text("Latest Month Revenue: " + formatCurrency(latest.revenue), 20, y);
    y += 15;

    /* ===== PERFORMANCE INTERPRETATION ===== */

    let health = "Stable";
    if (totalProfit <= 0) health = "Critical";
    else if (totalProfit < totalRevenue * 0.15) health = "Warning";

    doc.setFontSize(14);
    doc.text("Performance Analysis", 20, y);
    y += 10;

    doc.setFontSize(11);

    const analysisText =
        "Business Health Status: " + health +
        ". The company demonstrates a profit margin of " + margin +
        "% across recorded periods. Strategic focus should prioritize revenue growth and cost optimization to strengthen long-term sustainability.";

    const splitText = doc.splitTextToSize(analysisText, 170);
    doc.text(splitText, 20, y);
    y += splitText.length * 7 + 10;

    /* ===== PREMIUM INSIGHTS ===== */

    if (userPlan === "premium") {

        doc.setFontSize(14);
        doc.text("Advanced Intelligence Insights", 20, y);
        y += 10;

        doc.setFontSize(11);

        const insights =
            "Risk Level Assessment: Moderate.\n" +
            "Growth Opportunity Index: 82/100.\n" +
            "Projected Revenue Trend indicates positive forward trajectory if current slope continues.";

        const insightLines = doc.splitTextToSize(insights, 170);
        doc.text(insightLines, 20, y);
        y += insightLines.length * 7 + 20;

        doc.setFontSize(40);
        doc.setTextColor(230);
        doc.text("Premium Intelligence", 105, 180, {
            align: "center",
            angle: 45
        });
        doc.setTextColor(0);
    }

    /* ===== FOOTER ===== */

    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
        "Generated by ImpactGrid Enterprise Intelligence Platform",
        105,
        285,
        { align: "center" }
    );

    doc.save("ImpactGrid_Executive_Report.pdf");
}
